PKBL.Web/Controllers/MasterCabPropController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PKBL.Domain.Entities.Master;
using PKBL.Infrastructure.Persistence;

namespace PKBL.Web.Controllers
{
    public class MasterCabPropController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MasterCabPropController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: MasterCabProp
        public async Task<IActionResult> Index()
        {
            return View(await _context.M_CabProps.Where(x=>!x.IsDeleted).ToListAsync());
        }

        // GET: MasterCabProp/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var m_CabProp = await _context.M_CabProps
                .FirstOrDefaultAsync(m => m.Id == id);
            if (m_CabProp == null)
            {
                return NotFound();
            }

            return View(m_CabProp);
        }

        // GET: MasterCabProp/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: MasterCabProp/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Cabang,Propinsi")] M_CabProp m_CabProp)
        {
            if (ModelState.IsValid)
            {
                _context.Add(m_CabProp);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(m_CabProp);
        }

        // GET: MasterCabProp/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var m_CabProp = await _context.M_CabProps.FindAsync(id);
            if (m_CabProp == null)
            {
                return NotFound();
            }
            return View(m_CabProp);
        }

        // POST: MasterCabProp/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,Cabang,Propinsi,CreatedBy,CreatedDate")] M_CabProp m_CabProp)
        {
            if (id != m_CabProp.Id || !M_CabPropExists(m_CabProp.Id))
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(m_CabProp);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!M_CabPropExists(m_CabProp.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(m_CabProp);
        }

        // GET: MasterCabProp/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var m_CabProp = await _context.M_CabProps
                .FirstOrDefaultAsync(m => m.Id == id);
            if (m_CabProp == null)
            {
                return NotFound();
            }

            return View(m_CabProp);
        }

        // POST: MasterCabProp/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var m_CabProp = await _context.M_CabProps.FindAsync(id);
            m_CabProp.IsDeleted = true;
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool M_CabPropExists(long id)
        {
            return _context.M_CabProps.Any(e => e.Id == id && !e.IsDeleted);
        }
    }
}

PKBL.Web/Controllers/MasterCompanyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PKBL.Domain.Entities.Master;
using PKBL.Infrastructure.Persistence;

namespace PKBL.Web.Controllers
{
    public class MasterCompanyController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MasterCompanyController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: MasterCompany
        public async Task<IActionResult> Index()
        {
            return View(await _context.M_Companies.Where(e=>!e.IsDeleted).ToListAsync());
        }

        // GET: MasterCompany/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var m_Company = await _context.M_Companies
                .FirstOrDefaultAsync(m => m.Id == id);
            if (m_Company == null)
            {
                return NotFound();
            }

            return View(m_Company);
        }

        // GET: MasterCompany/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: MasterCompany/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Description")] M_Company m_Company)
        {
            if (ModelState.IsValid)
            {
                _context.Add(m_Company);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(m_Company);
        }

        // GET: MasterCompany/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var m_Company = await _context.M_Companies.FindAsync(id);
            if (m_Company == null)
            {
                return NotFound();
            }
            return View(m_Company);
        }

        // POST: MasterCompany/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,Description,CreatedBy,CreatedDate")] M_Company m_Company)
        {
            if (id != m_Company.Id || !M_CompanyExists(m_Company.Id))
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(m_Company);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!M_CompanyExists(m_Company.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(m_Company);
        }

        // GET: MasterCompany/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var m_Company = await _context.M_Companies
                .FirstOrDefaultAsync(m => m.Id == id);
            if (m_Company == null)
            {
                return NotFound();
            }

            return View(m_Company);
        }

        // POST: MasterCompany/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var m_Company = await _context.M_Companies.FindAsync(id);
            m_Company.IsDeleted = true;;
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool M_CompanyExists(long id)
        {
            return _context.M_Companies.Any(e => e.Id == id && !e.IsDeleted);
        }
    }
}

PKBL.Web/Controllers/MasterMitraController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PKBL.Domain.Entities.Master;
using PKBL.Infrastructure.Persistence;

namespace PKBL.Web.Controllers
{
    public class MasterMitraController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MasterMitraController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: MasterMitra
        public async Task<IActionResult> Index()
        {
            return View(await _context.M_Mitras.Where(x=> !x.IsDeleted).ToListAsync());
        }

        // GET: MasterMitra/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var m_Mitra = await _context.M_Mitras
                .FirstOrDefaultAsync(m => m.Id == id);
            if (m_Mitra == null)
            {
                return NotFound();
            }

            return View(m_Mitra);
        }

        // GET: MasterMitra/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: MasterMitra/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,RequestorAddress,AddressDistrict,HomeOwnershipId,RequestorPhone1,RequestorPhone2,RequestorMail,MaritalStatusId,EducationLevelId,CompanyDataId,Family_Relative_ID,Other_Relative_ID,Car_Mortage_ID,Motorcycle_Mortage_ID,Other_Mortage_ID,MortageRemarks,Administrative_Id,Production_Activity_Id1,Production_Activity_Id2,Production_Activity_Id3,Production_Activity_Id4,IsProductHandMade,IsMachineMade,Owned_Tool1,Owned_Tool1_count,Owned_Tool2,Owned_Tool2_count,Owned_Tool3,Owned_Tool3_count,Owned_Tool4,Owned_Tool4_count,Service_Provided,Marketing,IsLocalMarket,IsExport,Checklist_Id,UploadedFile,InventoryUpdateId,MGRNoProposal,TglBermasalah")] M_Mitra m_Mitra)
        {
            if (ModelState.IsValid)
            {
                _context.Add(m_Mitra);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(m_Mitra);
        }

        // GET: MasterMitra/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var m_Mitra = await _context.M_Mitras.FindAsync(id);
            if (m_Mitra == null)
            {
                return NotFound();
            }
            return View(m_Mitra);
        }

        // POST: MasterMitra/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,RequestorAddress,AddressDistrict,HomeOwnershipId,RequestorPhone1,RequestorPhone2,RequestorMail,MaritalStatusId,EducationLevelId,CompanyDataId,Family_Relative_ID,Other_Relative_ID,Car_Mortage_ID,Motorcycle_Mortage_ID,Other_Mortage_ID,MortageRemarks,Administrative_Id,Production_Activity_Id1,Production_Activity_Id2,Production_Activity_Id3,Production_Activity_Id4,IsProductHandMade,IsMachineMade,Owned_Tool1,Owned_Tool1_count,Owned_Tool2,Owned_Tool2_count,Owned_Tool3,Owned_Tool3_count,Owned_Tool4,Owned_Tool4_count,Service_Provided,Marketing,IsLocalMarket,IsExport,Checklist_Id,UploadedFile,InventoryUpdateId,MGRNoProposal,TglBermasalah,CreatedBy,CreatedDate")] M_Mitra m_Mitra)
        {
            if (id != m_Mitra.Id || !M_MitraExists(m_Mitra.Id))
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(m_Mitra);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!M_MitraExists(m_Mitra.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(m_Mitra);
        }

        // GET: MasterMitra/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var m_Mitra = await _context.M_Mitras
                .FirstOrDefaultAsync(m => m.Id == id);
            if (m_Mitra == null)
            {
                return NotFound();
            }

            return View(m_Mitra);
        }

        // POST: MasterMitra/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var m_Mitra = await _context.M_Mitras.FindAsync(id);
            m_Mitra.IsDeleted = true;
            //_context.M_Mitras.Remove(m_Mitra);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool M_MitraExists(long id)
        {
            return _context.M_Mitras.Any(e => e.Id == id && !e.IsDeleted);
        }
    }
}

PKBL.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>:: PKBL ANTAM ::</title>

    <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/vendor/nprogress/css/nprogress.css" rel="stylesheet" />
    @RenderSection("Styles", required: false)
    <link href="~/css/custom.css" rel="stylesheet" />
</head>

<body class="nav-md">
    <div class="container body">
        <div class="main_container">
            <div class="col-md-3 left_col">
                <div class="left_col scroll-view">
                    <div class="navbar nav_title" style="border: 0">
                        <div class="text-center" style="padding-left:25%">
                            <h6>PKBL</h6>
                        </div>

                    </div>

                    <div class="clearfix"></div>


                    <div class="profile clearfix">
                        <div class="profile_pic" style="padding-left:1px; padding-right:1px">
                            <img style="position:center" src="~/images/antam2.png" />
                        </div>

                        <div class="clearfix"></div>
                    </div>


                    <br />


                    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                        <div class="menu_section">

                            <ul class="nav side-menu">
                                <li>
                                    <a asp-controller="Home"><i class="fa fa-home"></i> Home</a>
                                </li>
                                <li>
                                    <a><i class="fa fa-edit"></i> Master Data <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu">
                                        <li><a asp-controller="MasterCompany" asp-action="Index">Perusahaan</a></li>
                                        <li><a asp-controller="MasterDropdown" asp-action="Index">Drop Down</a></li>
                                        <li><a asp-controller="MasterJenisKreditKemitraan" asp-action="Index">Jenis Kredit Kemitraan</a></li>
                                        <li><a asp-controller="MasterKantorCabang" asp-action="Index">Kantor Cabang</a></li>
                                        <li><a asp-controller="MasterCabProp" asp-action="Index">Cab Prop</a></li>
                                        <li><a asp-controller="MasterKotaKabupaten" asp-action="Index">Kota Kabupaten</a></li>
                                        <li><a asp-controller="MasterMitra" asp-action="Index">Mitra</a></li>
                                        <li><a asp-controller="MasterProvince" asp-action="Index">Provinsi</a></li>
                                        <li><a asp-controller="MasterRefDataUsahaMitra" asp-action="Index">Ref Data Usaha Mitra</a></li>
                                        <li><a asp-controller="MasterSektorKemitraan" asp-action="Index">Sektor Kemitraan</a></li>
                                        <li><a asp-controller="MasterSupplier" asp-action="Index">Supplier</a></li>
                                    </ul>
                                </li>
                                @*<li>
                                        <a><i class="fa fa-desktop"></i> UI Elements <span class="fa fa-chevron-down"></span></a>
                                        <ul class="nav child_menu">
                                            <li><a href="general_elements.html">General Elements</a></li>
                                            <li><a href="media_gallery.html">Media Gallery</a></li>
                                            <li><a href="typography.html">Typography</a></li>
                                            <li><a href="icons.html">Icons</a></li>
                                            <li><a href="glyphicons.html">Glyphicons</a></li>
                                            <li><a href="widgets.html">Widgets</a></li>
                                            <li><a href="invoice.html">Invoice</a></li>
                                            <li><a href="inbox.html">Inbox</a></li>
                                            <li><a href="calendar.html">Calendar</a></li>
                                        </ul>
                                    </li>
                                    <li>
                                        <a><i class="fa fa-table"></i> Tables <span class="fa fa-chevron-down"></span></a>
                                        <ul class="nav child_menu">
                                            <li><a href="tables.html">Tables</a></li>
                                            <li><a href="tables_dynamic.html">Table Dynamic</a></li>
                                        </ul>
                                    </li>
                                    <li>
                                        <a><i class="fa fa-bar-chart-o"></i> Data Presentation <span class="fa fa-chevron-down"></span></a>
                                        <ul class="nav child_menu">
                                            <li><a href="chartjs.html">Chart JS</a></li>
                                            <li><a href="chartjs2.html">Chart JS2</a></li>
                                            <li><a href="morisjs.html">Moris JS</a></li>
                                            <li><a href="echarts.html">ECharts</a></li>
                                            <li><a href="other_charts.html">Other Charts</a></li>
                                        </ul>
                                    </li>
                                    <li>
                                        <a><i class="fa fa-clone"></i>Layouts <span class="fa fa-chevron-down"></span></a>
                                        <ul class="nav child_menu">
                                            <li><a href="fixed_sidebar.html">Fixed Sidebar</a></li>
                                            <li><a href="fixed_footer.html">Fixed Footer</a></li>
                                        </ul>
                                    </li>*@
                            </ul>
                        </div>
                        @*<div class="menu_section">

                                <ul class="nav side-menu">
                                    <li>
                                        <a><i class="fa fa-bug"></i> Additional Pages <span class="fa fa-chevron-down"></span></a>
                                        <ul class="nav child_menu">
                                            <li><a href="e_commerce.html">E-commerce</a></li>
                                            <li><a href="projects.html">Projects</a></li>
                                            <li><a href="project_detail.html">Project Detail</a></li>
                                            <li><a href="contacts.html">Contacts</a></li>
                                            <li><a href="profile.html">Profile</a></li>
                                        </ul>
                                    </li>
                                    <li>
                                        <a><i class="fa fa-windows"></i> Extras <span class="fa fa-chevron-down"></span></a>
                                        <ul class="nav child_menu">
                                            <li><a href="page_403.html">403 Error</a></li>
                                            <li><a href="page_404.html">404 Error</a></li>
                                            <li><a href="page_500.html">500 Error</a></li>
                                            <li><a href="plain_page.html">Plain Page</a></li>
                                            <li><a href="login.html">Login Page</a></li>
                                            <li><a href="pricing_tables.html">Pricing Tables</a></li>
                                        </ul>
                                    </li>
                                    <li>
                                        <a><i class="fa fa-sitemap"></i> Multilevel Menu <span class="fa fa-chevron-down"></span></a>
                                        <ul class="nav child_menu">
                                            <li>
                                                <a href="#level1_1">Level One</a>
                                            </li>
                                            <li>
                                                <a>Level One<span class="fa fa-chevron-down"></span></a>
                                                <ul class="nav child_menu">
                                                    <li class="sub_menu">
                                                        <a href="level2.html">Level Two</a>
                                                    </li>
                                                    <li>
                                                        <a href="#level2_1">Level Two</a>
                                                    </li>
                                                    <li>
                                                        <a href="#level2_2">Level Two</a>
                                                    </li>
                                                </ul>
                                            </li>
                                            <li>
                                                <a href="#level1_2">Level One</a>
                                            </li>
                                        </ul>
                                    </li>

                                </ul>
                            </div>*@

                    </div>

                </div>
            </div>

            <!-- top navigation -->
            <div class="top_nav">
                <div class="nav_menu">
                    <div class="nav toggle">
                        <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                    </div>
                    <nav class="nav navbar-nav">
                        <ul class=" navbar-right">
                            <li class="nav-item dropdown open" style="padding-left: 15px;">
                                <a href="javascript:;" class="user-profile dropdown-toggle" aria-haspopup="true" id="navbarDropdown" data-toggle="dropdown" aria-expanded="false">
                                    <img src="images/user.png" alt="">logon user
                                </a>
                                <div class="dropdown-menu dropdown-usermenu pull-right" aria-labelledby="navbarDropdown">

                                    <a class="dropdown-item" href="javascript:;">Change Password</a>
                                    <a class="dropdown-item" href="login.html"><i class="fa fa-sign-out pull-right"></i> Log Out</a>
                                </div>
                            </li>


                        </ul>
                    </nav>
                </div>
            </div>
            <!-- /top navigation -->
            <!-- page content -->
            <div class="right_col" role="main">
                <div class="">
                    @RenderBody()

                </div>
            </div>
            <!-- /page content -->
            <!-- footer content -->
            <footer>
                <div class="align-content-center">
                    PT. Siap Technovation Unggul <a href="http://www.stu.co.id/"></a>
                </div>
                <div class="clearfix"></div>
            </footer>
            <!-- /footer content -->
        </div>
    </div>



    <script src="~/vendor/Jquery/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/vendor/fastclick/fastclick.js"></script>
    <script src="~/vendor/nprogress/js/nprogress.js"></script>
    <script src="~/js/custom.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>